export * from './manage/company-manage.component';
export * from './overview/detail/company-overview.component'
export * from './address/detail/company-address.component';
export * from './overview/upsert/upsert-company-overview.component';
export * from './address/upsert/upsert-company-address.component';
export * from './department/detail/department-detail.component';
export * from './department/upsert/upsert-department.component';
export * from './designation/detail/designation-detail.component';
export * from './designation/upsert/upsert-designation.component';
